baseURL = "/"
languageCode = "en-US"
title = "French Malware Analyst"
theme = "hugo-sustain"
highlight = true 
enableEmoji = true
plausible_analytics_domain = "naptax.github.io"

[permalinks]
  post = "/:slug"

[params]
  avatar = "/images/wopr.png"
  author = "nAptaX"
  description = "Don't Panic : R E V E R S E"
  plausible_analytics_domain = "naptax.github.io"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "naptax@proton.me"
  Twitter       = "_naptax"
  Telegram      = "naptax"

