baseURL = "/"
languageCode = "en-US"
title = "French Malware Analyst"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
theme = "hugo-sustain"
highlight = true 

[permalinks]
  post = "/:slug"

[params]
  avatar = "/images/wopr.png"
  author = "nAptaX"
  description = "Don't Panic : R E V E R S E"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "naptax@proton.me"
  Twitter       = "_naptax"
  Telegram      = "naptax"

